### ISSUE TITLE
crash 1.19.4 fabric server

### ISSUE THREAD

**Issue by nea-c** [PotatoPresident/HeadIndex#10]
When installing with the following mods
`fabricLoader 0.14.19`
`fabricAPI 0.78.0` `lithium 0.11.1` `Pehkui 3.7.2` `WorldEdit 7.2.14`

Don't have any custom data packs installed, but they still show as failed to load

```
...
[09:54:46] [ForkJoinPool.commonPool-worker-1/INFO]: Loading food-drinks heads from cache
[09:54:46] [ForkJoinPool.commonPool-worker-1/INFO]: Loading humans heads from cache
[09:54:46] [ForkJoinPool.commonPool-worker-1/INFO]: Loading humanoid heads from cache
[09:54:46] [ForkJoinPool.commonPool-worker-1/INFO]: Loading miscellaneous heads from cache
[09:54:46] [ForkJoinPool.commonPool-worker-1/INFO]: Loading monsters heads from cache
[09:54:46] [ForkJoinPool.commonPool-worker-1/INFO]: Loading plants heads from cache
[09:54:46] [ForkJoinPool.commonPool-worker-1/INFO]: Finished loading 52010 heads
[09:54:46] [main/INFO]: Registering commands with com.sk89q.worldedit.fabric.FabricPlatform
[09:54:46] [main/INFO]: Loaded 7 recipes
[09:54:47] [main/INFO]: Loaded 1179 advancements
[09:54:47] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Receiver class fr.catcore.server.translations.api.resource.language.SystemDelegatedLanguage does not define or inherit an implementation of the resolved method 'abstract java.lang.String method_4679(java.lang.String, java.lang.String)' of abstract class net.minecraft.class_2477.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:209) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.19.jar:?]
Caused by: java.lang.AbstractMethodError: Receiver class fr.catcore.server.translations.api.resource.language.SystemDelegatedLanguage does not define or inherit an implementation of the resolved method 'abstract java.lang.String method_4679(java.lang.String, java.lang.String)' of abstract class net.minecraft.class_2477.
	at net.minecraft.class_2477.method_48307(class_2477.java:89) ~[server-intermediary.jar:?]
	at net.minecraft.class_2588.method_11025(class_2588.java:55) ~[server-intermediary.jar:?]
	at net.minecraft.class_2588.method_27659(class_2588.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_2561.method_27657(class_2561.java:112) ~[server-intermediary.jar:?]
	at net.minecraft.class_5348.getString(class_5348.java:91) ~[server-intermediary.jar:?]
	at net.minecraft.class_2561.getString(class_2561.java:51) ~[server-intermediary.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.lambda$reload$2(ServerTranslations.java:176) ~[server_translations_api-1.4.19+1.19.3-ef3dbc4ca52a7c18.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

```

**Comment by PotatoPresident** [comment]
I keep meaning to release a new version, for now add this mod

https://github.com/NucleoidMC/Server-Translations/releases/tag/v2.0.0-beta.2%2B1.19.4-pre2

**Comment by nea-c** [comment]
Thanks!
Installed successfully!
